# Generated by Django 3.0.5 on 2020-11-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_dl_ds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml',
            name='short_desc',
            field=models.TextField(),
        ),
    ]
