# Generated by Django 3.0.5 on 2020-11-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20201121_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dl',
            name='short_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ds',
            name='short_desc',
            field=models.TextField(),
        ),
    ]
