# Generated by Django 3.0.5 on 2020-11-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_ds_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dl',
            name='photo',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
