# Generated by Django 3.0.5 on 2020-11-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_dl_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ds',
            name='photo',
            field=models.ImageField(default='', upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='ml',
            name='photo',
            field=models.ImageField(default='', upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='dl',
            name='photo',
            field=models.ImageField(default='', upload_to='static/img'),
        ),
    ]
